-- SQL запрос для заполнения специализаций (100 значений)
INSERT INTO specializations (name) VALUES
('Frontend Developer'),
('Backend Developer'),
('Full Stack Developer'),
('Mobile Developer'),
('iOS Developer'),
('Android Developer'),
('React Native Developer'),
('Flutter Developer'),
('DevOps Engineer'),
('Cloud Engineer'),
('AWS Specialist'),
('Azure Specialist'),
('Google Cloud Specialist'),
('Docker Specialist'),
('Kubernetes Specialist'),
('Linux Administrator'),
('System Administrator'),
('Network Engineer'),
('Security Engineer'),
('Cybersecurity Specialist'),
('Penetration Tester'),
('Data Engineer'),
('Data Scientist'),
('Machine Learning Engineer'),
('AI Engineer'),
('Deep Learning Specialist'),
('NLP Specialist'),
('Computer Vision Specialist'),
('Blockchain Developer'),
('Smart Contract Developer'),
('Solidity Developer'),
('Web3 Developer'),
('Game Developer'),
('Unity Developer'),
('Unreal Engine Developer'),
('VR Developer'),
('AR Developer'),
('QA Engineer'),
('Test Automation Engineer'),
('Performance Tester'),
('Security Tester'),
('UI/UX Designer'),
('Product Designer'),
('Graphic Designer'),
('3D Designer'),
('Motion Designer'),
('Product Manager'),
('Project Manager'),
('Scrum Master'),
('Business Analyst'),
('Data Analyst'),
('Business Intelligence Specialist'),
('Database Administrator'),
('SQL Developer'),
('NoSQL Specialist'),
('MongoDB Specialist'),
('PostgreSQL Specialist'),
('MySQL Specialist'),
('Redis Specialist'),
('Elasticsearch Specialist'),
('Big Data Engineer'),
('Hadoop Specialist'),
('Spark Specialist'),
('Kafka Specialist'),
('Microservices Architect'),
('Solution Architect'),
('Enterprise Architect'),
('Technical Lead'),
('Engineering Manager'),
('CTO'),
('Technical Writer'),
('Developer Advocate'),
('Community Manager'),
('Sales Engineer'),
('Pre-sales Engineer'),
('Support Engineer'),
('Site Reliability Engineer'),
('Infrastructure Engineer'),
('Platform Engineer'),
('API Developer'),
('Integration Specialist'),
('E-commerce Developer'),
('WordPress Developer'),
('Shopify Developer'),
('Magento Developer'),
('CMS Specialist'),
('SEO Specialist'),
('Digital Marketing Specialist'),
('Content Creator'),
('Video Editor'),
('Photographer'),
('Social Media Manager'),
('Growth Hacker'),
('Conversion Rate Optimizer'),
('Email Marketing Specialist'),
('PPC Specialist'),
('Analytics Specialist'),
('Marketing Automation Specialist'),
('CRM Specialist'),
('Salesforce Specialist'),
('HubSpot Specialist');

-- SQL запрос для заполнения скиллов (100 значений)
INSERT INTO skills (name) VALUES
('JavaScript'),
('TypeScript'),
('Python'),
('Java'),
('C++'),
('C#'),
('Go'),
('Rust'),
('PHP'),
('Ruby'),
('Swift'),
('Kotlin'),
('Dart'),
('HTML'),
('CSS'),
('SCSS/SASS'),
('React'),
('Vue.js'),
('Angular'),
('Next.js'),
('Nuxt.js'),
('Node.js'),
('Express.js'),
('NestJS'),
('Django'),
('Flask'),
('FastAPI'),
('Spring Boot'),
('Laravel'),
('Symfony'),
('Ruby on Rails'),
('ASP.NET'),
('.NET Core'),
('GraphQL'),
('REST API'),
('gRPC'),
('WebSocket'),
('Redis'),
('MongoDB'),
('PostgreSQL'),
('MySQL'),
('SQLite'),
('Oracle'),
('Elasticsearch'),
('Docker'),
('Kubernetes'),
('Jenkins'),
('GitLab CI/CD'),
('GitHub Actions'),
('Terraform'),
('Ansible'),
('AWS'),
('Azure'),
('Google Cloud'),
('Linux'),
('Windows Server'),
('Git'),
('GitHub'),
('GitLab'),
('Bitbucket'),
('Jira'),
('Confluence'),
('Agile'),
('Scrum'),
('Kanban'),
('Machine Learning'),
('Deep Learning'),
('TensorFlow'),
('PyTorch'),
('Scikit-learn'),
('Pandas'),
('NumPy'),
('Matplotlib'),
('Seaborn'),
('Jupyter'),
('Apache Spark'),
('Hadoop'),
('Kafka'),
('RabbitMQ'),
('Nginx'),
('Apache'),
('Webpack'),
('Vite'),
('Babel'),
('ESLint'),
('Prettier'),
('Jest'),
('Cypress'),
('Selenium'),
('Playwright'),
('Postman'),
('Swagger'),
('Figma'),
('Adobe XD'),
('Sketch'),
('Photoshop'),
('Illustrator'),
('Blender'),
('Unity'),
('Unreal Engine'),
('Solidity'),
('Web3.js'),
('Ethers.js'),
('Truffle'),
('Hardhat');

-- SQL запрос для добавления подкатегорий к категориям 20-28
-- Подкатегории для категории 20 (Unreal Engine)
INSERT INTO categories (id, name, parent_id) VALUES
(29, 'Blueprint Scripting', 20),
(30, 'C++ Development', 20),
(31, 'Game Mechanics', 20),
(32, 'Character Animation', 20),
(33, 'Level Design', 20),
(34, 'Environment Art', 20),
(35, 'UI/UX Design', 20),
(36, 'Multiplayer Development', 20),
(37, 'VR Development', 20),
(38, 'AR Development', 20),
(39, 'Performance Optimization', 20),
(40, 'Shaders & Materials', 20),
(41, 'Audio Integration', 20),
(42, 'Physics Simulation', 20),
(43, 'AI Programming', 20),
(44, 'Mobile Game Development', 20),
(45, 'Console Development', 20),
(46, 'Procedural Generation', 20),
(47, 'Cinematics & Cutscenes', 20),
(48, 'Game Testing', 20),
(49, 'Asset Pipeline', 20),
(50, 'Plugin Development', 20),
(51, 'Networking & Replication', 20),
(52, 'Save System', 20),
(53, 'Inventory System', 20),
(54, 'Combat System', 20),
(55, 'Quest System', 20),
(56, 'Dialogue System', 20),
(57, 'Tutorial System', 20),
(58, 'Localization', 20);

-- Подкатегории для категории 21 (Unity3D)
INSERT INTO categories (id, name, parent_id) VALUES
(59, 'C# Scripting', 21),
(60, 'Game Development', 21),
(61, 'Mobile Game Development', 21),
(62, '2D Game Development', 21),
(63, '3D Game Development', 21),
(64, 'AR Development', 21),
(65, 'VR Development', 21),
(66, 'Character Controller', 21),
(67, 'Animation System', 21),
(68, 'Physics & Collision', 21),
(69, 'UI System', 21),
(70, 'Shader Development', 21),
(71, 'Asset Store Integration', 21),
(72, 'Multiplayer Networking', 21),
(73, 'Performance Optimization', 21),
(74, 'Build & Deployment', 21),
(75, 'Audio System', 21),
(76, 'Particle Effects', 21),
(77, 'Lighting & Rendering', 21),
(78, 'Terrain Generation', 21),
(79, 'Procedural Generation', 21),
(80, 'AI & Pathfinding', 21),
(81, 'Save System', 21),
(82, 'Analytics Integration', 21),
(83, 'Ad Integration', 21),
(84, 'IAP System', 21),
(85, 'Cloud Services', 21),
(86, 'Editor Tools', 21),
(87, 'Custom Inspector', 21),
(88, 'Package Manager', 21);

-- Подкатегории для категории 22 (AI Websites & Software)
INSERT INTO categories (id, name, parent_id) VALUES
(89, 'AI Chatbots', 22),
(90, 'AI Dashboards', 22),
(91, 'AI Content Generators', 22),
(92, 'AI Image Generators', 22),
(93, 'AI Text Generators', 22),
(94, 'AI Code Generators', 22),
(95, 'AI Analytics Platforms', 22),
(96, 'AI Recommendation Systems', 22),
(97, 'AI Search Engines', 22),
(98, 'AI E-commerce Platforms', 22),
(99, 'AI CRM Systems', 22),
(100, 'AI Project Management', 22),
(101, 'AI Learning Platforms', 22),
(102, 'AI Healthcare Software', 22),
(103, 'AI Finance Software', 22),
(104, 'AI Marketing Tools', 22),
(105, 'AI Customer Support', 22),
(106, 'AI Data Visualization', 22),
(107, 'AI Automation Tools', 22),
(108, 'AI Personalization', 22),
(109, 'AI Voice Assistants', 22),
(110, 'AI Video Generators', 22),
(111, 'AI Music Generators', 22),
(112, 'AI Translation Services', 22),
(113, 'AI Transcription Services', 22),
(114, 'AI Document Processing', 22),
(115, 'AI Form Builders', 22),
(116, 'AI Survey Tools', 22);

-- Подкатегории для категории 23 (AI Integrations)
INSERT INTO categories (id, name, parent_id) VALUES
(117, 'OpenAI API Integration', 23),
(118, 'GPT Integration', 23),
(119, 'Claude API Integration', 23),
(120, 'Google AI Integration', 23),
(121, 'Azure AI Integration', 23),
(122, 'AWS AI Integration', 23),
(123, 'Computer Vision API', 23),
(124, 'Natural Language Processing', 23),
(125, 'Speech Recognition API', 23),
(126, 'Text-to-Speech API', 23),
(127, 'Image Recognition API', 23),
(128, 'Sentiment Analysis API', 23),
(129, 'Translation API', 23),
(130, 'Chatbot Integration', 23),
(131, 'Recommendation Engine', 23),
(132, 'Fraud Detection API', 23),
(133, 'Face Recognition API', 23),
(134, 'OCR Integration', 23),
(135, 'Voice Assistant Integration', 23),
(136, 'AI Analytics Integration', 23),
(137, 'Machine Learning API', 23),
(138, 'Deep Learning Integration', 23),
(139, 'TensorFlow Integration', 23),
(140, 'PyTorch Integration', 23),
(141, 'Custom AI Model Integration', 23),
(142, 'AI Workflow Automation', 23),
(143, 'AI Data Pipeline', 23),
(144, 'AI Model Deployment', 23);

-- Подкатегории для категории 24 (AI Mobile Apps)
INSERT INTO categories (id, name, parent_id) VALUES
(145, 'iOS AI Apps', 24),
(146, 'Android AI Apps', 24),
(147, 'AI Photo Editing Apps', 24),
(148, 'AI Video Editing Apps', 24),
(149, 'AI Voice Assistant Apps', 24),
(150, 'AI Language Learning Apps', 24),
(151, 'AI Fitness Apps', 24),
(152, 'AI Health Apps', 24),
(153, 'AI Productivity Apps', 24),
(154, 'AI Shopping Apps', 24),
(155, 'AI Social Media Apps', 24),
(156, 'AI Music Apps', 24),
(157, 'AI Camera Apps', 24),
(158, 'AI Navigation Apps', 24),
(159, 'AI News Apps', 24),
(160, 'AI Finance Apps', 24),
(161, 'AI Education Apps', 24),
(162, 'AI Gaming Apps', 24),
(163, 'AI AR Apps', 24),
(164, 'AI VR Apps', 24),
(165, 'AI Chat Apps', 24),
(166, 'AI Translation Apps', 24),
(167, 'AI Note-Taking Apps', 24),
(168, 'AI Calendar Apps', 24),
(169, 'AI Weather Apps', 24),
(170, 'AI Travel Apps', 24),
(171, 'AI Food Apps', 24),
(172, 'AI Dating Apps', 24);

-- Подкатегории для категории 25 (AI Technology Consulting)
INSERT INTO categories (id, name, parent_id) VALUES
(173, 'AI Strategy Consulting', 25),
(174, 'AI Implementation', 25),
(175, 'AI Architecture Design', 25),
(176, 'AI Model Selection', 25),
(177, 'AI Training & Development', 25),
(178, 'AI Performance Optimization', 25),
(179, 'AI Security Consulting', 25),
(180, 'AI Ethics Consulting', 25),
(181, 'AI Compliance', 25),
(182, 'AI Data Strategy', 25),
(183, 'AI Infrastructure Setup', 25),
(184, 'AI Cloud Migration', 25),
(185, 'AI Cost Optimization', 25),
(186, 'AI ROI Analysis', 25),
(187, 'AI Risk Assessment', 25),
(188, 'AI Vendor Selection', 25),
(189, 'AI Team Building', 25),
(190, 'AI Best Practices', 25),
(191, 'AI Governance', 25),
(192, 'AI Audit Services', 25),
(193, 'AI Transformation', 25),
(194, 'AI Innovation Consulting', 25),
(195, 'AI Research & Development', 25),
(196, 'AI Proof of Concept', 25),
(197, 'AI Pilot Projects', 25),
(198, 'AI Scaling Strategy', 25),
(199, 'AI Maintenance & Support', 25),
(200, 'AI Training Programs', 25);

-- Подкатегории для категории 26 (Website Design)
INSERT INTO categories (id, name, parent_id) VALUES
(201, 'Responsive Design', 26),
(202, 'E-commerce Design', 26),
(203, 'Landing Page Design', 26),
(204, 'Portfolio Design', 26),
(205, 'Corporate Website Design', 26),
(206, 'Blog Design', 26),
(207, 'News Website Design', 26),
(208, 'Restaurant Website Design', 26),
(209, 'Hotel Website Design', 26),
(210, 'Medical Website Design', 26),
(211, 'Educational Website Design', 26),
(212, 'Non-profit Website Design', 26),
(213, 'Real Estate Website Design', 26),
(214, 'Fashion Website Design', 26),
(215, 'Entertainment Website Design', 26),
(216, 'Sports Website Design', 26),
(217, 'Music Website Design', 26),
(218, 'Art Gallery Design', 26),
(219, 'Event Website Design', 26),
(220, 'SaaS Website Design', 26),
(221, 'Dashboard Design', 26),
(222, 'Admin Panel Design', 26),
(223, 'Mobile-First Design', 26),
(224, 'Dark Mode Design', 26),
(225, 'Minimalist Design', 26),
(226, 'Modern Design', 26),
(227, 'Vintage Design', 26),
(228, 'Accessibility Design', 26);

-- Подкатегории для категории 27 (UX Design)
INSERT INTO categories (id, name, parent_id) VALUES
(229, 'User Research', 27),
(230, 'User Interviews', 27),
(231, 'User Personas', 27),
(232, 'User Journey Mapping', 27),
(233, 'Wireframing', 27),
(234, 'Prototyping', 27),
(235, 'Information Architecture', 27),
(236, 'Usability Testing', 27),
(237, 'A/B Testing', 27),
(238, 'Interaction Design', 27),
(239, 'Visual Design', 27),
(240, 'Mobile UX Design', 27),
(241, 'Web UX Design', 27),
(242, 'App UX Design', 27),
(243, 'E-commerce UX', 27),
(244, 'SaaS UX Design', 27),
(245, 'Enterprise UX', 27),
(246, 'Accessibility Design', 27),
(247, 'Conversion Optimization', 27),
(248, 'Onboarding Design', 27),
(249, 'Error Handling Design', 27),
(250, 'Form Design', 27),
(251, 'Navigation Design', 27),
(252, 'Search UX', 27),
(253, 'Content Strategy', 27),
(254, 'Micro-interactions', 27),
(255, 'Design Systems', 27),
(256, 'UX Writing', 27);

-- Подкатегории для категории 28 (Landing Page Design)
INSERT INTO categories (id, name, parent_id) VALUES
(257, 'Conversion Optimization', 28),
(258, 'A/B Testing', 28),
(259, 'Hero Section Design', 28),
(260, 'Call-to-Action Design', 28),
(261, 'Lead Generation Forms', 28),
(262, 'Product Landing Pages', 28),
(263, 'Service Landing Pages', 28),
(264, 'Event Landing Pages', 28),
(265, 'App Landing Pages', 28),
(266, 'SaaS Landing Pages', 28),
(267, 'E-commerce Landing Pages', 28),
(268, 'Email Signup Pages', 28),
(269, 'Webinar Landing Pages', 28),
(270, 'Course Landing Pages', 28),
(271, 'Book Landing Pages', 28),
(272, 'Crowdfunding Pages', 28),
(273, 'Coming Soon Pages', 28),
(274, '404 Error Pages', 28),
(275, 'Thank You Pages', 28),
(276, 'Mobile Landing Pages', 28),
(277, 'Video Landing Pages', 28),
(278, 'Interactive Landing Pages', 28),
(279, 'Animated Landing Pages', 28),
(280, 'Minimalist Landing Pages', 28),
(281, 'Bold Landing Pages', 28),
(282, 'Trust Building Elements', 28),
(283, 'Social Proof Design', 28),
(284, 'Testimonial Sections', 28),
(285, 'Pricing Page Design', 28),
(286, 'FAQ Sections', 28);

