"""Add portfolio

Revision ID: 1374275ed115
Revises: 
Create Date: 2025-12-03 14:03:54.859200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1374275ed115'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'users', ['client_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['developer_id'], ['id'])
    op.create_foreign_key(None, 'project_images', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'project_reviews', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'project_reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'project_skills', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'project_tags', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'user_reviews', 'users', ['reviewer_id'], ['id'])
    op.create_foreign_key(None, 'user_reviews', 'users', ['reviewed_user_id'], ['id'])
    op.create_foreign_key(None, 'user_skills', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_specializations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_specializations', type_='foreignkey')
    op.drop_constraint(None, 'user_skills', type_='foreignkey')
    op.drop_constraint(None, 'user_reviews', type_='foreignkey')
    op.drop_constraint(None, 'user_reviews', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'project_tags', type_='foreignkey')
    op.drop_constraint(None, 'project_skills', type_='foreignkey')
    op.drop_constraint(None, 'project_reviews', type_='foreignkey')
    op.drop_constraint(None, 'project_reviews', type_='foreignkey')
    op.drop_constraint(None, 'project_images', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    # ### end Alembic commands ###
