"""Lazy Category

Revision ID: 3f090bc33f3d
Revises: 4fb36f4bfa64
Create Date: 2026-01-06 17:57:55.614287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f090bc33f3d'
down_revision: Union[str, Sequence[str], None] = '4fb36f4bfa64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'type',
               existing_type=sa.TEXT(),
               nullable=True, server_default="message")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'type',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
