"""Update Order

Revision ID: 416ca8ebf5ae
Revises: 5b0fa37dd266
Create Date: 2026-01-13 22:49:46.131470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '416ca8ebf5ae'
down_revision: Union[str, Sequence[str], None] = '5b0fa37dd266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('message_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['message_id'])
    op.create_foreign_key(None, 'orders', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'message_id')
    # ### end Alembic commands ###
