"""Indexes

Revision ID: 4a4fee718007
Revises: e4f7068af53e
Create Date: 2026-03-10 23:28:31.740983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4fee718007'
down_revision: Union[str, Sequence[str], None] = 'e4f7068af53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comments_author_created', 'comments', ['author_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index('ix_comments_created_deleted', 'comments', ['created_at', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_comments_deleted_at'), 'comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_comments_is_deleted'), 'comments', ['is_deleted'], unique=False)
    op.create_index('ix_comments_post_author', 'comments', ['post_id', 'author_id'], unique=False)
    op.create_index('ix_comments_post_created', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_updated_at'), 'comments', ['updated_at'], unique=False)
    op.create_index('ix_notifications_actor_created', 'notifications', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_actor_id'), 'notifications', ['actor_id'], unique=False)
    op.create_index(op.f('ix_notifications_expires_at'), 'notifications', ['expires_at'], unique=False)
    op.create_index('ix_notifications_expires_unread', 'notifications', ['expires_at', 'status'], unique=False)
    op.create_index(op.f('ix_notifications_post_id'), 'notifications', ['post_id'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_user_status_created', 'notifications', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_type_created', 'notifications', ['user_id', 'type', 'created_at'], unique=False)
    op.create_index('ix_posts_author_created', 'posts', ['author_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index('ix_posts_author_status', 'posts', ['author_id', 'status'], unique=False)
    op.create_index('ix_posts_category_created', 'posts', ['category', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index('ix_posts_created_deleted', 'posts', ['created_at', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_posts_deleted_at'), 'posts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_posts_is_deleted'), 'posts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_posts_is_reply'), 'posts', ['is_reply'], unique=False)
    op.create_index('ix_posts_saved_count_created', 'posts', ['saved_count', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index('ix_posts_status_published', 'posts', ['status', 'published'], unique=False)
    op.create_index(op.f('ix_posts_updated_at'), 'posts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_posts_views'), 'posts', ['views'], unique=False)
    op.create_index('ix_posts_views_created', 'posts', ['views', 'created_at'], unique=False)
    op.create_index(op.f('ix_saved_posts_post_id'), 'saved_posts', ['post_id'], unique=False)
    op.create_index('ix_saved_posts_post_saved', 'saved_posts', ['post_id', 'saved_at'], unique=False)
    op.create_index(op.f('ix_saved_posts_saved_at'), 'saved_posts', ['saved_at'], unique=False)
    op.create_index(op.f('ix_saved_posts_user_id'), 'saved_posts', ['user_id'], unique=False)
    op.create_index('ix_saved_posts_user_saved', 'saved_posts', ['user_id', 'saved_at'], unique=False)
    op.create_unique_constraint('uq_saved_post_user_post', 'saved_posts', ['user_id', 'post_id'])
    op.create_index(op.f('ix_votes_created_at'), 'votes', ['created_at'], unique=False)
    op.create_index('ix_votes_post_created', 'votes', ['post_id', 'created_at'], unique=False)
    op.create_index('ix_votes_post_value', 'votes', ['post_id', 'value'], unique=False)
    op.create_index('ix_votes_user_created', 'votes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_votes_value'), 'votes', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_value'), table_name='votes')
    op.drop_index('ix_votes_user_created', table_name='votes')
    op.drop_index('ix_votes_post_value', table_name='votes')
    op.drop_index('ix_votes_post_created', table_name='votes')
    op.drop_index(op.f('ix_votes_created_at'), table_name='votes')
    op.drop_constraint('uq_saved_post_user_post', 'saved_posts', type_='unique')
    op.drop_index('ix_saved_posts_user_saved', table_name='saved_posts')
    op.drop_index(op.f('ix_saved_posts_user_id'), table_name='saved_posts')
    op.drop_index(op.f('ix_saved_posts_saved_at'), table_name='saved_posts')
    op.drop_index('ix_saved_posts_post_saved', table_name='saved_posts')
    op.drop_index(op.f('ix_saved_posts_post_id'), table_name='saved_posts')
    op.drop_index('ix_posts_views_created', table_name='posts')
    op.drop_index(op.f('ix_posts_views'), table_name='posts')
    op.drop_index(op.f('ix_posts_updated_at'), table_name='posts')
    op.drop_index('ix_posts_status_published', table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index('ix_posts_saved_count_created', table_name='posts')
    op.drop_index(op.f('ix_posts_is_reply'), table_name='posts')
    op.drop_index(op.f('ix_posts_is_deleted'), table_name='posts')
    op.drop_index(op.f('ix_posts_deleted_at'), table_name='posts')
    op.drop_index('ix_posts_created_deleted', table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index('ix_posts_category_created', table_name='posts')
    op.drop_index('ix_posts_author_status', table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_index('ix_posts_author_created', table_name='posts')
    op.drop_index('ix_notifications_user_type_created', table_name='notifications')
    op.drop_index('ix_notifications_user_status_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_post_id'), table_name='notifications')
    op.drop_index('ix_notifications_expires_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_expires_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_actor_id'), table_name='notifications')
    op.drop_index('ix_notifications_actor_created', table_name='notifications')
    op.drop_index(op.f('ix_comments_updated_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index('ix_comments_post_created', table_name='comments')
    op.drop_index('ix_comments_post_author', table_name='comments')
    op.drop_index(op.f('ix_comments_is_deleted'), table_name='comments')
    op.drop_index(op.f('ix_comments_deleted_at'), table_name='comments')
    op.drop_index('ix_comments_created_deleted', table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_index('ix_comments_author_created', table_name='comments')
    # ### end Alembic commands ###
