"""New message col

Revision ID: 4fb36f4bfa64
Revises: 7f6094fb3246
Create Date: 2026-01-05 11:14:11.021430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb36f4bfa64'
down_revision: Union[str, Sequence[str], None] = '7f6094fb3246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('type', sa.Text(), nullable=False, server_default="text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'type')
    # ### end Alembic commands ###
