"""Orders Delete status

Revision ID: 513d676e9e91
Revises: 46d288e0d541
Create Date: 2025-11-16 14:33:11.355345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '513d676e9e91'
down_revision: Union[str, Sequence[str], None] = '46d288e0d541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', postgresql.ENUM('pending', 'accepted', 'in_progress', 'completed', 'cancelled', name='orderstatusenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
