"""User was updated

Revision ID: 51506d618c0e
Revises: c66bce4be5b6
Create Date: 2025-11-13 00:21:07.347921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51506d618c0e'
down_revision: Union[str, Sequence[str], None] = 'c66bce4be5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'completed_orders',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'repeat_orders',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('users', 'repeat_orders',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'completed_orders',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
