"""NeW

Revision ID: 53cffb517779
Revises: 348bdddb6eb1
Create Date: 2025-11-18 09:09:51.976632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53cffb517779'
down_revision: Union[str, Sequence[str], None] = '348bdddb6eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_project'), 'favorites', type_='unique')
    op.alter_column(
        'orders',
        'status',
        type_=sa.Enum('open', 'closed', 'in_progress', 'completed', 'cancelled', 'paid', name='status_enum'),
        postgresql_using='status::text::status_enum',
        existing_type=postgresql.ENUM('open', 'closed', 'in_progress', 'completed', 'cancelled', 'paid', name='status'),
        existing_nullable=False
    )
    op.alter_column('projects', 'budget',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column(
        'projects',
        'crypto_type',
        type_=sa.Integer(),
        postgresql_using='crypto_type::integer',
        existing_type=sa.String(),
        existing_nullable=False
    )
    op.alter_column(
        'users',
        'role',
        type_=sa.Enum('developer', 'customer', name='user_role_enum'),
        postgresql_using='role::text::user_role_enum',
        existing_type=sa.String(),
        existing_nullable=False
    )
    op.alter_column('users', 'status',
                type_=sa.Enum('online', 'offline', name='user_status_enum'),
                postgresql_using='role::text::user_status_enum',
                existing_type=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.Enum('online', 'offline', name='user_status_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('developer', 'customer', name='user_role_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('projects', 'crypto_type',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'budget',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('open', 'closed', 'in_progress', 'completed', 'cancelled', 'paid', name='status_enum'),
               type_=postgresql.ENUM('open', 'closed', 'in_progress', 'completed', 'cancelled', 'paid', name='status'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_user_project'), 'favorites', ['user_id', 'project_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
