"""add new field

Revision ID: 5c37b50d462b
Revises: ee9cf69e8838
Create Date: 2025-12-26 14:30:41.539174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c37b50d462b'
down_revision: Union[str, Sequence[str], None] = 'ee9cf69e8838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'none', name='request_status_enum'), nullable=False, server_default='none'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'status')
    # ### end Alembic commands ###
