"""Update project

Revision ID: 674d65e4ca3b
Revises: 3f090bc33f3d
Create Date: 2026-01-12 23:57:21.927911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674d65e4ca3b'
down_revision: Union[str, Sequence[str], None] = '3f090bc33f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    job_type_enum = sa.Enum(
        'hourly',
        'fixed',
        name='job_type_enum'
    )
    job_type_enum.create(op.get_bind(), checkfirst=True)    
    op.add_column(
        'projects',
        sa.Column(
            'job_type',
            job_type_enum,
            nullable=False,
            server_default='fixed'
        )
    )
    op.add_column('projects', sa.Column('hourly_rate_min', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('hourly_rate_max', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('isConsultation', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('experience_level', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('total_request_count', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('users', 'request_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('request_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('users', 'total_request_count')
    op.drop_column('projects', 'experience_level')
    op.drop_column('projects', 'isConsultation')
    op.drop_column('projects', 'hourly_rate_max')
    op.drop_column('projects', 'hourly_rate_min')
    op.drop_column('projects', 'job_type')
    # ### end Alembic commands ###
