"""Tags was added

Revision ID: 6a5687fa6529
Revises: 16dbdd68f023
Create Date: 2025-11-14 14:07:09.755011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5687fa6529'
down_revision: Union[str, Sequence[str], None] = '16dbdd68f023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('visible', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()))
    op.add_column('projects', sa.Column('moderation_status', sa.String(), nullable=False, server_default=sa.sql.expression.true()))
    op.add_column('projects', sa.Column('views_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('projects', sa.Column('external_links', sa.Text(), nullable=True))
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('projects', 'external_links')
    op.drop_column('projects', 'views_count')
    op.drop_column('projects', 'moderation_status')
    op.drop_column('projects', 'visible')
    # ### end Alembic commands ###
