"""Add status to Orders

Revision ID: 80b869064604
Revises: 513d676e9e91
Create Date: 2025-11-16 14:34:00.164086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b869064604'
down_revision: Union[str, Sequence[str], None] = '513d676e9e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('open', 'closed', 'in_progress', 'completed', 'cancelled', 'paid', name='orderstatusenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
