"""User table was updated

Revision ID: 83757cc349d8
Revises: aa972511257e
Create Date: 2025-11-12 11:43:22.876839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83757cc349d8'
down_revision: Union[str, Sequence[str], None] = 'aa972511257e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banner_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(), nullable=True, server_default='active'))
    # Если есть необходимость, можно выполнить UPDATE (хотя дефолт уже установит значение для новых записей)
    op.execute("UPDATE users SET status = 'active' WHERE status IS NULL")
    # Меняем столбец на не-nullable
    op.alter_column('users', 'status', nullable=False, server_default=None)
    op.add_column('users', sa.Column('region', sa.String(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('completed_orders', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('repeat_orders', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('users_wallet_address_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.create_unique_constraint(op.f('users_wallet_address_key'), 'users', ['wallet_address'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'verified')
    op.drop_column('users', 'rating')
    op.drop_column('users', 'repeat_orders')
    op.drop_column('users', 'completed_orders')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'region')
    op.drop_column('users', 'status')
    op.drop_column('users', 'description')
    op.drop_column('users', 'banner_url')
