"""New fields post

Revision ID: 9c625e33fb15
Revises: 
Create Date: 2026-03-07 18:08:59.745670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c625e33fb15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.Enum('SENT', 'REJECTED', 'ACCEPTED', 'UNSENT', name='poststatus'), nullable=False, server_default="UNSENT"))
    op.add_column('posts', sa.Column('benefit', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('aiOrigin', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('linkUrl', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'linkUrl')
    op.drop_column('posts', 'aiOrigin')
    op.drop_column('posts', 'benefit')
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
