"""Project review

Revision ID: c66bce4be5b6
Revises: 83757cc349d8
Create Date: 2025-11-12 13:40:02.045522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66bce4be5b6'
down_revision: Union[str, Sequence[str], None] = '83757cc349d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('crypto_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('reviews_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_favorite')
    op.drop_column('projects', 'reviews_count')
    op.drop_column('projects', 'rating')
    op.drop_column('projects', 'crypto_type')
    # ### end Alembic commands ###
