"""vv

Revision ID: ee9cf69e8838
Revises: 
Create Date: 2025-12-26 14:22:28.266012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9cf69e8838'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'none', name='request_status_enum'), nullable=False, server_default='none'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'status')
    # ### end Alembic commands ###
